### ISSUE TITLE
The discount codes for Sip doesn't work

### ISSUE THREAD

**Issue by rampatra** [danmindru/rare-big-deal#65]
Link - https://rarebigdeal.com/products/sip

**Comment by danmindru** [comment]
hey @ruiaureliano,

Will you look into it? Thanks!

**Comment by rampatra** [comment]
Sure, no worries. Btw, you tagged the wrong person.

**Comment by ruiaureliano** [comment]
@rampatra it should be working now, thanks @danmindru
